---

- hosts: all
  tasks:
  
  - ec2:
     key_name: Edureka-VirtualBox
     instance_type: t2.micro
     image: ami-0a313d6098716f372
     region: us-east-1
     wait: yes
     group: launch-wizard-1
     count: "{{ instance_count }}"
     vpc_subnet_id: subnet-07e3446a64270686a 
     assign_public_ip: yes
     instance_tags:
       app-module: "{{ app_module }}"
       env: "{{ environment_name }}"
       app: "{{ app_name }}"
       owner: "{{ app_owner }}"

